build:
    environment:
        php:
            version: 8.1.12
            ini:
                xdebug.mode: off
    image: default-bionic
    nodes:
        php81:
            environment:
                php:
                    version: 8.1.12
                    ini:
                        xdebug.mode: off
                        pecl_extensions:
                            - pcov

filter:
    paths:
        - "src/*"

tools:
    external_code_coverage:
        timeout: 600
    php_loc: true
    php_pdepend: true
    php_sim: true
    php_changetracking: true
